class Keyword < BaseModel
  include PupenextSingleTableInheritance

  self.table_name         = :avainsana
  self.primary_key        = :tunnus
  self.inheritance_column = :laji

  validates :selite, presence: true

  def self.default_child_instance
    child_class :ALV
  end

  def self.child_class_names
    {
      AIHEAL_LAATUAS:  Keyword,
      AIHEAL_LUVLIS:   Keyword,
      ALV:             Keyword::Vat,
      ALVULK:          Keyword::ForeignVat,
      ASAVAINSANA:     Keyword,
      ASIAKASHINNASTO: Keyword,
      ASIAKASLUOKKA:   Keyword,
      ASIAKASOSASTO:   Keyword::CustomerCategory,
      ASIAKASRYHMA:    Keyword::CustomerSubcategory,
      ASIAKASTILA:     Keyword,
      ASIAKHIN_ATTR:   Keyword::CustomerPriceListAttribute,
      C:               Keyword,
      CRM_HAAS:        Keyword,
      CRM_ROOLI:       Keyword,
      CRM_SUORAMARKKI: Keyword,
      DPAVAINSANALAJI: Keyword,
      ELINKAARI:       Keyword,
      EXTASAVAINSANA:  Keyword,
      EXTRANET_TEEMA:  Keyword,
      GS1_SSCC:        Keyword,
      HAE_JA_SELAA:    Keyword,
      HAMMASTUS:       Keyword,
      HENKILO_OSASTO:  Keyword,
      HINNAT_CRON:     Keyword,
      INVASTEPAIKKA:   Keyword,
      INVEN_LAJI:      Keyword,
      INVLISTA_OSTRY:  Keyword,
      JAKELULISTA:     Keyword,
      JTVALMISVIESTI:  Keyword,
      KAANTALVVIESTI:  Keyword,
      KALETAPA:        Keyword,
      KARHUVIESTI:     Keyword,
      KATEISOTTO:      Keyword,
      KERAYSERA_TK:    Keyword,
      KERAYSLISTA:     Keyword,
      KM:              Keyword,
      KOHDE_TYYPPI:    Keyword,
      KONEENOSA:       Keyword,
      KOPIOITUOTE:     Keyword,
      KT:              Keyword::NatureOfTransaction,
      KUKAASEMA:       Keyword,
      KUNTA:           Keyword,
      KVERITTELY:      Keyword,
      LAANI:           Keyword,
      LABEL:           Keyword,
      LAHETETYYPPI:    Keyword::PackingListType,
      LASKUKUVAUS:     Keyword,
      LASKUTUS_SAATE:  Keyword,
      LISATIETO:       Keyword::ProductInformationType,
      LITETY:          Keyword,
      LITETY_LAATUAS:  Keyword,
      LITETY_LUVLIS:   Keyword,
      LITETY_TKIRJAST: Keyword,
      LUETTELO:        Keyword,
      MAARATOIMPAIKKA: Keyword,
      MAARYHMA:        Keyword,
      MAINOSTXT_LASKU: Keyword,
      MAKSUEHTOKV:     Keyword::TermsOfPaymentTranslation,
      MALLI:           Keyword,
      MALLITARKENNE:   Keyword,
      MYSQLALIAS:      Keyword::CustomAttribute,
      MYYNNISTA_OSTO:  Keyword,
      OLETUSPAIKKA:    Keyword,
      OPTISCANKOM:     Keyword,
      OSASTO:          Product::Category,
      OSTOTIL_TILTYYP: Keyword,
      PAIKALLISVARAST: Keyword,
      PAKKAUSKV:       Keyword::PackageTranslation,
      PALAUTUS_SAATE:  Keyword,
      PARAMETRI:       Keyword::ProductParameterType,
      PIIRI:           Keyword,
      PS_ALA_TRY:      Keyword,
      PUUTEKOMM:       Keyword,
      RAHTIKIRJA:      Keyword,
      RAJATOIMIPAIKAT: Keyword,
      RELEX_TUOTEPAR:  Keyword,
      RESEPTI_KENTAT:  Keyword,
      REVENUEREP:      Keyword::RevenueExpenditure,
      S:               Product::Status,
      SAHKTILTUN:      Keyword,
      SALDOVAHVISTUS:  Keyword,
      SARJANUMERON_LI: Keyword,
      SEURANTA:        Keyword,
      SIIRTO_VASTNRO:  Keyword,
      SIIRTOVARASTOT:  Keyword,
      SOP_LAITLUET:    Keyword,
      SOPIMUS_KENTTA:  Keyword,
      SSCC:            Keyword,
      TARJOUS_VAKIOTE: Keyword,
      TARRATYYPPI:     Keyword,
      TERMINAALIALUE:  Keyword,
      THR:             Keyword,
      TIL:             Keyword,
      TOIM_TAPA_TA:    Keyword,
      TOIMEHTO:        Keyword,
      TOIMIT_TKIRJAST: Keyword,
      TOIMITTAJARYHMA: Keyword,
      TOIMITUSTAPA_OS: Keyword,
      TOIMMYYNTI:      Keyword,
      TOIMTAPAKV:      Keyword,
      TOIMTAPALP:      Keyword,
      TOIMVAHVISTUS:   Keyword,
      TRIVITYYPPI:     Keyword,
      TRY:             Product::Subcategory,
      TULLI:           Keyword,
      TUOTE_EXP_CRON:  Keyword,
      TUOTEMERKKI:     Product::Brand,
      TUOTEULK:        Keyword::ProductKeywordType,
      TV:              Keyword,
      TV_LISATIETO:    Keyword,
      TYOM_PRIORIT:    Keyword,
      TYOM_TYOJONO:    Keyword,
      TYOM_TYOKENTAT:  Keyword,
      TYOM_TYOLINJA:   Keyword,
      TYOM_TYOSTATUS:  Keyword,
      TYOMVALMVIEST:   Keyword,
      ULKJARJLAHETE:   Keyword,
      VAKIOVIESTI:     Keyword,
      VAKIOVIESTI_TIL: Keyword,
      VALMISTUSLINJA:  Keyword,
      VARASTOLUOKKA:   Keyword,
      VARASTORYHMA:    Keyword,
      VARTOIMTULOSTIN: Keyword,
      Y:               Keyword,
    }.stringify_keys
  end
end
